#!/bin/bash

#$ -l h_fsize=2G
#$ -l h_vmem=10G
#$ -l h_rt=160:00:00
#$ -e /nfs/dust/ilc/user/airqui/RecoLogs/stdError_ttJ_xNAMEjob.txt
#$ -o /nfs/dust/ilc/user/airqui/RecoLogs/stdOutput_ttJ_xNAMEjob.txt
#$ -m ebas
#$ -M adrian.irles@desy.de

cd /nfs/dust/ilc/user/airqui/ttJ/uwer_calc
source setup.sh

cd ttj_calc/objs/x86_64/gnu

./main.exe --lhc --sqrtshad=7000 --topmass xMASS --scale xSCALE xPROCESS --ktmin 50 --vegaspoints xVEGAS --dist > results_15october/caracola
