#!/bin/bash
 
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export MASS="160"
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export SCALE="1.0"
export muSCALE="mu1"
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo " "
echo "----------------------"
echo mass"="$MASS
echo scale"="$muSCALE
echo " "

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo born processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# BORN  PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--leadingorder --virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo virtual processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# VIRTUAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo real processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--real --proc 0"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc0"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 1"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc1"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 3"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc3"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 6"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc6"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 7"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc7"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 8"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc8"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 9"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc9"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 11"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc11"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 13"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc13"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 14"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc14"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 15"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc15"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 17"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc17"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo subtraction processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SUBTRACTION PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--subtractions --proc 18"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc18"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

export PROCESS="--subtractions --proc 20"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc20"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 21"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc21"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 24"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc24"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 


####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export SCALE="0.5"
export muSCALE="mu05"
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo " "
echo "----------------------"
echo mass"="$MASS
echo scale"="$muSCALE
echo " "

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo born processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# BORN  PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--leadingorder --virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo virtual processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# VIRTUAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo real processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--real --proc 0"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc0"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 1"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc1"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 3"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc3"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 6"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc6"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 7"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc7"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 8"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc8"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 9"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc9"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 11"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc11"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 13"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc13"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 14"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc14"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 15"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc15"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 17"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc17"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo subtraction processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SUBTRACTION PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--subtractions --proc 18"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc18"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

export PROCESS="--subtractions --proc 20"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc20"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 21"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc21"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 24"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc24"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 




####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export SCALE="2.0"
export muSCALE="mu2"
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo " "
echo "----------------------"
echo mass"="$MASS
echo scale"="$muSCALE
echo " "

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo born processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# BORN  PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--leadingorder --virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--leadingorder --virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_born_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo virtual processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# VIRTUAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--virtual --gg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --gqb"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_gqb"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--virtual --qg"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_virtual_qg"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="20000"
echo real processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REAL PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--real --proc 0"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc0"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 1"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc1"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 3"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc3"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 6"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc6"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 7"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc7"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 8"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc8"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 9"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc9"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 11"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc11"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 13"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc13"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 14"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc14"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 15"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc15"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--real --proc 17"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_real_proc17"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export VEGAS="30000"
echo subtraction processes with VEGAS"="$VEGAS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SUBTRACTION PROCESSES, 
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export PROCESS="--subtractions --proc 18"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc18"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------

export PROCESS="--subtractions --proc 20"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc20"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 21"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc21"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

#----------
export PROCESS="--subtractions --proc 24"
export NAMEjob="mt"$MASS"_CT10_"$muSCALE"_pt50_"$VEGAS"_subtractions_proc24"
                                                                                                        
source modifyJOB
qsub jobtest_$NAMEjob
rm jobtest_$NAMEjob 

