#!/bin/bash

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 160
rename mt160.5 mt160_plus05 *mu320_*
rename mt159.5 mt160_minus05 *mu320_*
rename mu320 mu2 *320_*

rename mt160.5 mt160_plus05 *mu80_*
rename mt159.5 mt160_minus05 *mu80_*
rename mu80 mu05 *mu80_*

rename mt160.5 mt160_plus05 *mu160_*
rename mt159.5 mt160_minus05 *mu160_*
rename mu160 mu1 *mu160_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 161
rename mt161.5 mt161_plus05 *mu322_*
rename mt160.5 mt161_minus05 *mu322_*
rename mu322 mu2 *322_*

rename mt161.5 mt161_plus05 *mu80.5_*
rename mt160.5 mt161_minus05 *mu80.5_*
rename mu80.5 mu05 *mu80.5_*

rename mt161.5 mt161_plus05 *mu161_*
rename mt160.5 mt161_minus05 *mu161_*
rename mu161 mu1 *mu161_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 162
rename mt162.5 mt162_plus05 *mu324_*
rename mt161.5 mt162_minus05 *mu324_*
rename mu324 mu2 *324_*

rename mt162.5 mt162_plus05 *mu81_*
rename mt161.5 mt162_minus05 *mu81_*
rename mu81 mu05 *mu81_*

rename mt162.5 mt162_plus05 *mu162_*
rename mt161.5 mt162_minus05 *mu162_*
rename mu162 mu1 *mu162_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 163
rename mt163.5 mt163_plus05 *mu326_*
rename mt162.5 mt163_minus05 *mu326_*
rename mu326 mu2 *326_*

rename mt163.5 mt163_plus05 *mu81.5_*
rename mt162.5 mt163_minus05 *mu81.5_*
rename mu81.5 mu05 *mu81.5_*

rename mt163.5 mt163_plus05 *mu163_*
rename mt162.5 mt163_minus05 *mu163_*
rename mu163 mu1 *mu163_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 164

rename mt164.5 mt164_plus05 *mu02_*
rename mt163.5 mt164_minus05 *mu02_*

rename mt164.5 mt164_plus05 *mu03_*
rename mt163.5 mt164_minus05 *mu03_*

rename mt164.5 mt164_plus05 *mu07_*
rename mt163.5 mt164_minus05 *mu07_*

rename mt164.5 mt164_plus05 *mu3_*
rename mt163.5 mt164_minus05 *mu3_*

rename mt164.5 mt164_plus05 *mu4_*
rename mt163.5 mt164_minus05 *mu4_*

rename mt164.5 mt164_plus05 *mu8_*
rename mt163.5 mt164_minus05 *mu8_*

rename mt164.5 mt164_plus05 *mu328_*
rename mt163.5 mt164_minus05 *mu328_*
rename mu328 mu2 *328_*

rename mt164.5 mt164_plus05 *mu82_*
rename mt163.5 mt164_minus05 *mu82_*
rename mu82 mu05 *mu82_*

rename mt164.5 mt164_plus05 *mu164_*
rename mt163.5 mt164_minus05 *mu164_*
rename mu164 mu1 *mu164_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 165
rename mt165.5 mt165_plus05 *mu330_*
rename mt164.5 mt165_minus05 *mu330_*
rename mu330 mu2 *330_*

rename mt165.5 mt165_plus05 *mu82.5_*
rename mt164.5 mt165_minus05 *mu82.5_*
rename mu82.5 mu05 *mu82.5_*

rename mt165.5 mt165_plus05 *mu165_*
rename mt164.5 mt165_minus05 *mu165_*
rename mu165 mu1 *mu165_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 166
rename mt166.5 mt166_plus05 *mu332_*
rename mt163.5 mt166_minus05 *mu332_*
rename mu332 mu2 *332_*

rename mt166.5 mt166_plus05 *mu83_*
rename mt163.5 mt166_minus05 *mu83_*
rename mu83 mu05 *mu83_*

rename mt166.5 mt166_plus05 *mu166_*
rename mt163.5 mt166_minus05 *mu166_*
rename mu166 mu1 *mu166_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 167
rename mt167.5 mt167_plus05 *mu334_*
rename mt166.5 mt167_minus05 *mu334_*
rename mu334 mu2 *334_*

rename mt167.5 mt167_plus05 *mu83.5_*
rename mt166.5 mt167_minus05 *mu83.5_*
rename mu83.5 mu05 *mu83.5_*

rename mt167.5 mt167_plus05 *mu167_*
rename mt166.5 mt167_minus05 *mu167_*
rename mu167 mu1 *mu167_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 168
rename mt168.5 mt168_plus05 *mu336_*
rename mt167.5 mt168_minus05 *mu336_*
rename mu336 mu2 *336_*

rename mt168.5 mt168_plus05 *mu84_*
rename mt167.5 mt168_minus05 *mu84_*
rename mu84 mu05 *mu84_*

rename mt168.5 mt168_plus05 *mu168_*
rename mt167.5 mt168_minus05 *mu168_*
rename mu168 mu1 *mu168_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 169
rename mt169.5 mt169_plus05 *mu338_*
rename mt168.5 mt169_minus05 *mu338_*
rename mu338 mu2 *338_*

rename mt169.5 mt169_plus05 *mu84.5_*
rename mt168.5 mt169_minus05 *mu84.5_*
rename mu84.5 mu05 *mu84.5_*

rename mt169.5 mt169_plus05 *mu169_*
rename mt168.5 mt169_minus05 *mu169_*
rename mu169 mu1 *mu169_*

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## scale 170
rename mt170.5 mt170_plus05 *mu340_*
rename mt169.5 mt170_minus05 *mu340_*
rename mu340 mu2 *340_*

rename mt170.5 mt170_plus05 *mu85_*
rename mt169.5 mt170_minus05 *mu85_*
rename mu85 mu05 *mu85_*

rename mt170.5 mt170_plus05 *mu170_*
rename mt169.5 mt170_minus05 *mu170_*
rename mu170 mu1 *mu170_*